// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPP.Data;

namespace WebAPP.Migrations
{
    [DbContext(typeof(WebAPPContext))]
    partial class WebAPPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebAPP.Models.Product", b =>
                {
                    b.Property<int>("Cod_Produto")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NomeProduto");

                    b.Property<int>("Preco");

                    b.Property<int>("Quantidade");

                    b.Property<string>("Sexo");

                    b.Property<string>("Tamanho");

                    b.Property<int>("TaxaIVA");

                    b.Property<string>("Tipo");

                    b.HasKey("Cod_Produto");

                    b.ToTable("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
